import React from 'react'

const updateForm = (props) => {
  ;<form
    onSubmit={this.handleUpdateAlbumSubmit}
    className="adminForm"
    key={this.state.album_id}
  >
    <input
      type="text"
      name="title"
      onChange={this.handleTitle2Change}
      defaultValue={this.state.title}
    />
    <input
      type="text"
      name="artist"
      onChange={this.handleArtistChange}
      defaultValue={this.state.title}
    />
    <input
      type="text"
      name="image"
      onChange={this.handleImageChange}
      defaultValue={this.state.title}
    />
    <input
      type="text"
      name="format"
      onChange={this.handleFormatChange}
      defaultValue={this.state.title}
    />
    <input
      type="text"
      name="cat"
      onChange={this.handleCatChange}
      defaultValue={this.state.title}
    />
    <input
      type="text"
      name="label"
      onChange={this.handleLabelChange}
      defaultValue={this.state.title}
    />
    <input
      type="number"
      name="price"
      onChange={this.handlePriceChange}
      defaultValue={this.state.title}
    />
    <input
      type="number"
      name="releaseDate"
      onChange={this.handleReleasedateChange}
      defaultValue={this.state.title}
    />
    <input
      type="number"
      name="quantity"
      onChange={this.handleQuantityChange}
      defaultValue={this.state.title}
    />
    <input
      type="number"
      name="copies_sold"
      onChange={this.handleCopiesSoldChange}
      defaultValue={this.state.title}
    />
    <input type="submit" value="Update Album" />
  </form>
}

export default updateForm
